### ISSUE TITLE
Amélioration des bornes maxi taille acceptées en LD1 et LF

### ISSUE THREAD

**Issue by pascalcauquil** [OB7-IRD/akado#2]
Amélioration des bornes maxi taille acceptées en LD1 et LF

**Comment by tchemit** [comment]
Voir controle fr.ird.akado.observe.inspector.sample.LengthClassInspector

**Comment by pascalcauquil** [comment]
[BORNES A PASSER EN REVUE AVEC @Antoine-Duparc. Il faut sûrement apporter de la nuance par espèce sur les LD1]

L'idée est d'appliquer les bornes suivantes au-delà desquelles Akado retournera un warning ou une erreur :
* aux mesures LF : warning au-delà de 80 cm, , quelque soit l'espèce
* aux mesures LF : erreur au-delà de 120 cm, quelque soit l'espèce
* aux mesures LD1 : warning au-delà de 40 cm, quelque soit l'espèce
* aux mesures LD1 : erreur au-delà de 45 cm, quelque soit l'espèce

**Comment by Antoine-Duparc** [comment]
> [BORNES A PASSER EN REVUE AVEC @Antoine-Duparc. Il faut sûrement apporter de la nuance par espèce sur les LD1]

Si l'on veut être vraiment bon pour les LF et les LD1, je pense qu'il faut prendre la moyenne générale de toutes les données en base pour une espèce donnée + 3 x  son écart type. Cela donne une probabilité de 99.73 % d'avoir un point dedans. 
on peut prendre déjà ça pour un warning car donc en théorie il y 0.27% de chance d'être en dehors de la distribution de taille, donc peut de chance de ce tromper. 
Après pour l'erreur, on pourra ajouter un petit delta à définir genre 10% d'erreur. 

c'est seuil ne devrait pas trop changer dans le future vu la quantité de données que l'on a déjà.

**Comment by pascalcauquil** [comment]
Sur les données OA/OI 2000-2022 la requêtes suivante : 
```
SELECT 
smt.code,
sp.faocode,
min(ssm.sizeclass),
max(ssm.sizeclass)

FROM ps_logbook.samplespeciesmeasure ssm
inner join ps_logbook.samplespecies ss on (ssm.samplespecies=ss.topiaid)
inner join common.sizemeasuretype smt on (ss.sizemeasuretype=smt.topiaid)
inner join common.species sp on (ss.species=sp.topiaid)
inner join ps_logbook.sample s on (ss.sample=s.topiaid)
inner join ps_common.trip t on (s.trip=t.topiaid)

WHERE extract(year from t.enddate) >= 2000

GROUP BY
smt.code,
sp.faocode

ORDER BY
smt.code,
sp.faocode
```

Donne : 
<img width="236" alt="image" src="https://github.com/OB7-IRD/akado/assets/64549487/a1e4ff3d-4ccf-4586-93d7-5dc829e8eeb9">

Nous prendrons donc les valeurs suivantes : 

measuretype | faocode | min found in 2000-2022 | max found in 2000-2022 | min error | min warning | max warning | max error
-- | -- | -- | -- | -- | -- | -- | --
FL | ALB | 31,0 | 107,0 | 15,0 | 30,0 | 80,0 | 120,0
PD1 | ALB | 21,5 | 45,5 | 15,0 | 20,0 | 45,0 | 50,0
FL | BET | 21,0 | 180,0 | 15,0 | 20,0 | 80,0 | 190,0
PD1 | BET | 18,0 | 57,0 | 10,0 | 15,0 | 60,0 | 65,0
FL | SKJ | 20,0 | 97,0 | 15,0 | 18,0 | 80,0 | 110,0
PD1 | SKJ | 24,0 | 27,0 | 15,0 | 20,0 | 30,0 | 35,0
FL | YFT | 20,0 | 191,0 | 15,0 | 18,0 | 80,0 | 200,0
PD1 | YFT | 10,5 | 60,0 | 8,0 | 10,0 | 60,0 | 70,0
FL | FRI | 21,0 | 80,0 | 15,0 | 20,0 | 80,0 | 90,0
FL | FRZ | 33,0 | 46,0 | 15,0 | 30,0 | 45,0 | 50,0
FL | KAW | 25,0 | 82,0 | 15,0 | 22,0 | 80,0 | 90,0
FL | LTA | 28,0 | 77,0 | 15,0 | 25,0 | 75,0 | 90,0
  |   |   |   |   |   |   |  
FL | tout autre |   |   | 5,0 | 10,0 | 80,0 | 400,0
PD1 | tout autre |   |   | 5,0 | 10,0 | 70,0 | 100,0

Ce valeurs vont nécessairement faire différer les résultats d'Akado sur ObServe et sur AVDTH.

@tchemit Si ça fait trop de cas, s'il faut simplifier, on en parle, c'est possible.

**Comment by tchemit** [comment]
@pascalcauquil sur ce contrôle particulier, cela ne me pose pas de problème que les résultats diffèrent vue la simplicité du contrôle.

Cela fait beaucoup de cas (par rapport à l'existant...), mais bon je viens de le coder ;)

**Comment by tchemit** [comment]
Par contre il faudra que tu regardes comment mettre ça en place dans la feuille de calcul de résultat, le code est très cryptique et je ne sais vraiment pas quoi faire.

Ça se trouve dans la classe ```fr.ird.akado.observe.result.SampleResult```

```java
for (SampleSpeciesMeasure sampleSpeciesFrequency : ss.getSampleSpeciesMeasure()) {
                        hasErrorOnSampleSpeciesFrequency = false;
                        lengthClassCount = sampleSpeciesFrequency.getSizeClass() + "(" + sampleSpeciesFrequency.getCount() + ")";
                        ssfSpeciesCode = "";
                        if (!ObserveSampleInspector.specieMustBeSampled(species.getCode())) {
                            ssfSpeciesCode += "?";
                            hasErrorOnSampleSpeciesFrequency = true;
                        }
                        ssfSpeciesCode += species.getCode();
                        if (LengthClassInspector.lengthClassLimits(species, sampleSpeciesFrequency)) {
                            ssfSpeciesCode += " ?LD1";
                            hasErrorOnSampleSpeciesFrequency = true;
                        }
```

La méthode ```LengthClassInspector.lengthClassLimits``` était l'ancienne méthode qui ne testait que l'ancien cas...

**Comment by pascalcauquil** [comment]
Colonne max warning mise à jour
